/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedUsersRouteImport } from './routes/admin/_authed/users'
import { Route as AdminAuthedDevTablesRouteImport } from './routes/admin/_authed/dev/tables'
import { Route as AdminAuthedDevServerOpsRouteImport } from './routes/admin/_authed/dev/server-ops'
import { Route as AdminAuthedDevErdRouteImport } from './routes/admin/_authed/dev/erd'
import { Route as AdminAuthedDevArchitectureRouteImport } from './routes/admin/_authed/dev/architecture'
import { Route as AdminAuthedDevApiDocsRouteImport } from './routes/admin/_authed/dev/api-docs'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedUsersRoute = AdminAuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevTablesRoute = AdminAuthedDevTablesRouteImport.update({
  id: '/dev/tables',
  path: '/dev/tables',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevServerOpsRoute = AdminAuthedDevServerOpsRouteImport.update({
  id: '/dev/server-ops',
  path: '/dev/server-ops',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevErdRoute = AdminAuthedDevErdRouteImport.update({
  id: '/dev/erd',
  path: '/dev/erd',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevArchitectureRoute =
  AdminAuthedDevArchitectureRouteImport.update({
    id: '/dev/architecture',
    path: '/dev/architecture',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedDevApiDocsRoute = AdminAuthedDevApiDocsRouteImport.update({
  id: '/dev/api-docs',
  path: '/dev/api-docs',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/ocr': typeof OcrRoute
  '/recommend': typeof RecommendRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminAuthedUsersRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/dev/tables': typeof AdminAuthedDevTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/ocr': typeof OcrRoute
  '/recommend': typeof RecommendRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminAuthedUsersRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/dev/tables': typeof AdminAuthedDevTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/ocr': typeof OcrRoute
  '/recommend': typeof RecommendRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authed/users': typeof AdminAuthedUsersRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/_authed/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/_authed/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/_authed/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/_authed/dev/tables': typeof AdminAuthedDevTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/home'
    | '/map'
    | '/ocr'
    | '/recommend'
    | '/scan'
    | '/search'
    | '/settings'
    | '/admin'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
    | '/admin/dev/api-docs'
    | '/admin/dev/architecture'
    | '/admin/dev/erd'
    | '/admin/dev/server-ops'
    | '/admin/dev/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/home'
    | '/map'
    | '/ocr'
    | '/recommend'
    | '/scan'
    | '/search'
    | '/settings'
    | '/admin/login'
    | '/admin/users'
    | '/admin'
    | '/admin/dev/api-docs'
    | '/admin/dev/architecture'
    | '/admin/dev/erd'
    | '/admin/dev/server-ops'
    | '/admin/dev/tables'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/home'
    | '/map'
    | '/ocr'
    | '/recommend'
    | '/scan'
    | '/search'
    | '/settings'
    | '/admin/_authed'
    | '/admin/login'
    | '/admin/_authed/users'
    | '/admin/_authed/'
    | '/admin/_authed/dev/api-docs'
    | '/admin/_authed/dev/architecture'
    | '/admin/_authed/dev/erd'
    | '/admin/_authed/dev/server-ops'
    | '/admin/_authed/dev/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  OcrRoute: typeof OcrRoute
  RecommendRoute: typeof RecommendRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/users': {
      id: '/admin/_authed/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthedUsersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/tables': {
      id: '/admin/_authed/dev/tables'
      path: '/dev/tables'
      fullPath: '/admin/dev/tables'
      preLoaderRoute: typeof AdminAuthedDevTablesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/server-ops': {
      id: '/admin/_authed/dev/server-ops'
      path: '/dev/server-ops'
      fullPath: '/admin/dev/server-ops'
      preLoaderRoute: typeof AdminAuthedDevServerOpsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/erd': {
      id: '/admin/_authed/dev/erd'
      path: '/dev/erd'
      fullPath: '/admin/dev/erd'
      preLoaderRoute: typeof AdminAuthedDevErdRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/architecture': {
      id: '/admin/_authed/dev/architecture'
      path: '/dev/architecture'
      fullPath: '/admin/dev/architecture'
      preLoaderRoute: typeof AdminAuthedDevArchitectureRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/api-docs': {
      id: '/admin/_authed/dev/api-docs'
      path: '/dev/api-docs'
      fullPath: '/admin/dev/api-docs'
      preLoaderRoute: typeof AdminAuthedDevApiDocsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedUsersRoute: typeof AdminAuthedUsersRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedDevApiDocsRoute: typeof AdminAuthedDevApiDocsRoute
  AdminAuthedDevArchitectureRoute: typeof AdminAuthedDevArchitectureRoute
  AdminAuthedDevErdRoute: typeof AdminAuthedDevErdRoute
  AdminAuthedDevServerOpsRoute: typeof AdminAuthedDevServerOpsRoute
  AdminAuthedDevTablesRoute: typeof AdminAuthedDevTablesRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedUsersRoute: AdminAuthedUsersRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedDevApiDocsRoute: AdminAuthedDevApiDocsRoute,
  AdminAuthedDevArchitectureRoute: AdminAuthedDevArchitectureRoute,
  AdminAuthedDevErdRoute: AdminAuthedDevErdRoute,
  AdminAuthedDevServerOpsRoute: AdminAuthedDevServerOpsRoute,
  AdminAuthedDevTablesRoute: AdminAuthedDevTablesRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  OcrRoute: OcrRoute,
  RecommendRoute: RecommendRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
