/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedUsersRouteImport } from './routes/admin/_authed/users'
import { Route as AdminAuthedRobotsRouteImport } from './routes/admin/_authed/robots'
import { Route as AdminAuthedRobotRouteImport } from './routes/admin/_authed/robot'
import { Route as AdminAuthedPinkyDetectRouteImport } from './routes/admin/_authed/pinky-detect'
import { Route as AdminAuthedChatRouteImport } from './routes/admin/_authed/chat'
import { Route as AdminAuthedCameraRouteImport } from './routes/admin/_authed/camera'
import { Route as AdminAuthedBuzzerRouteImport } from './routes/admin/_authed/buzzer'
import { Route as AdminAuthedArmIndexRouteImport } from './routes/admin/_authed/arm/index'
import { Route as AdminAuthedDevTablesRouteImport } from './routes/admin/_authed/dev/tables'
import { Route as AdminAuthedDevServerOpsRouteImport } from './routes/admin/_authed/dev/server-ops'
import { Route as AdminAuthedDevErdRouteImport } from './routes/admin/_authed/dev/erd'
import { Route as AdminAuthedDevArchitectureRouteImport } from './routes/admin/_authed/dev/architecture'
import { Route as AdminAuthedDevApiDocsRouteImport } from './routes/admin/_authed/dev/api-docs'
import { Route as AdminAuthedArmJointControlRouteImport } from './routes/admin/_authed/arm/joint-control'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedUsersRoute = AdminAuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedRobotsRoute = AdminAuthedRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedRobotRoute = AdminAuthedRobotRouteImport.update({
  id: '/robot',
  path: '/robot',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedPinkyDetectRoute = AdminAuthedPinkyDetectRouteImport.update({
  id: '/pinky-detect',
  path: '/pinky-detect',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedChatRoute = AdminAuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedCameraRoute = AdminAuthedCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedBuzzerRoute = AdminAuthedBuzzerRouteImport.update({
  id: '/buzzer',
  path: '/buzzer',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedArmIndexRoute = AdminAuthedArmIndexRouteImport.update({
  id: '/arm/',
  path: '/arm/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevTablesRoute = AdminAuthedDevTablesRouteImport.update({
  id: '/dev/tables',
  path: '/dev/tables',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevServerOpsRoute = AdminAuthedDevServerOpsRouteImport.update({
  id: '/dev/server-ops',
  path: '/dev/server-ops',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevErdRoute = AdminAuthedDevErdRouteImport.update({
  id: '/dev/erd',
  path: '/dev/erd',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedDevArchitectureRoute =
  AdminAuthedDevArchitectureRouteImport.update({
    id: '/dev/architecture',
    path: '/dev/architecture',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedDevApiDocsRoute = AdminAuthedDevApiDocsRouteImport.update({
  id: '/dev/api-docs',
  path: '/dev/api-docs',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedArmJointControlRoute =
  AdminAuthedArmJointControlRouteImport.update({
    id: '/arm/joint-control',
    path: '/arm/joint-control',
    getParentRoute: () => AdminAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/buzzer': typeof AdminAuthedBuzzerRoute
  '/admin/camera': typeof AdminAuthedCameraRoute
  '/admin/chat': typeof AdminAuthedChatRoute
  '/admin/pinky-detect': typeof AdminAuthedPinkyDetectRoute
  '/admin/robot': typeof AdminAuthedRobotRoute
  '/admin/robots': typeof AdminAuthedRobotsRoute
  '/admin/users': typeof AdminAuthedUsersRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/arm/joint-control': typeof AdminAuthedArmJointControlRoute
  '/admin/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/dev/tables': typeof AdminAuthedDevTablesRoute
  '/admin/arm/': typeof AdminAuthedArmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/buzzer': typeof AdminAuthedBuzzerRoute
  '/admin/camera': typeof AdminAuthedCameraRoute
  '/admin/chat': typeof AdminAuthedChatRoute
  '/admin/pinky-detect': typeof AdminAuthedPinkyDetectRoute
  '/admin/robot': typeof AdminAuthedRobotRoute
  '/admin/robots': typeof AdminAuthedRobotsRoute
  '/admin/users': typeof AdminAuthedUsersRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/arm/joint-control': typeof AdminAuthedArmJointControlRoute
  '/admin/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/dev/tables': typeof AdminAuthedDevTablesRoute
  '/admin/arm': typeof AdminAuthedArmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authed/buzzer': typeof AdminAuthedBuzzerRoute
  '/admin/_authed/camera': typeof AdminAuthedCameraRoute
  '/admin/_authed/chat': typeof AdminAuthedChatRoute
  '/admin/_authed/pinky-detect': typeof AdminAuthedPinkyDetectRoute
  '/admin/_authed/robot': typeof AdminAuthedRobotRoute
  '/admin/_authed/robots': typeof AdminAuthedRobotsRoute
  '/admin/_authed/users': typeof AdminAuthedUsersRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/arm/joint-control': typeof AdminAuthedArmJointControlRoute
  '/admin/_authed/dev/api-docs': typeof AdminAuthedDevApiDocsRoute
  '/admin/_authed/dev/architecture': typeof AdminAuthedDevArchitectureRoute
  '/admin/_authed/dev/erd': typeof AdminAuthedDevErdRoute
  '/admin/_authed/dev/server-ops': typeof AdminAuthedDevServerOpsRoute
  '/admin/_authed/dev/tables': typeof AdminAuthedDevTablesRoute
  '/admin/_authed/arm/': typeof AdminAuthedArmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/buzzer'
    | '/admin/camera'
    | '/admin/chat'
    | '/admin/pinky-detect'
    | '/admin/robot'
    | '/admin/robots'
    | '/admin/users'
    | '/admin/'
    | '/admin/arm/joint-control'
    | '/admin/dev/api-docs'
    | '/admin/dev/architecture'
    | '/admin/dev/erd'
    | '/admin/dev/server-ops'
    | '/admin/dev/tables'
    | '/admin/arm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/buzzer'
    | '/admin/camera'
    | '/admin/chat'
    | '/admin/pinky-detect'
    | '/admin/robot'
    | '/admin/robots'
    | '/admin/users'
    | '/admin'
    | '/admin/arm/joint-control'
    | '/admin/dev/api-docs'
    | '/admin/dev/architecture'
    | '/admin/dev/erd'
    | '/admin/dev/server-ops'
    | '/admin/dev/tables'
    | '/admin/arm'
  id:
    | '__root__'
    | '/'
    | '/admin/_authed'
    | '/admin/login'
    | '/admin/_authed/buzzer'
    | '/admin/_authed/camera'
    | '/admin/_authed/chat'
    | '/admin/_authed/pinky-detect'
    | '/admin/_authed/robot'
    | '/admin/_authed/robots'
    | '/admin/_authed/users'
    | '/admin/_authed/'
    | '/admin/_authed/arm/joint-control'
    | '/admin/_authed/dev/api-docs'
    | '/admin/_authed/dev/architecture'
    | '/admin/_authed/dev/erd'
    | '/admin/_authed/dev/server-ops'
    | '/admin/_authed/dev/tables'
    | '/admin/_authed/arm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/users': {
      id: '/admin/_authed/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthedUsersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/robots': {
      id: '/admin/_authed/robots'
      path: '/robots'
      fullPath: '/admin/robots'
      preLoaderRoute: typeof AdminAuthedRobotsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/robot': {
      id: '/admin/_authed/robot'
      path: '/robot'
      fullPath: '/admin/robot'
      preLoaderRoute: typeof AdminAuthedRobotRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/pinky-detect': {
      id: '/admin/_authed/pinky-detect'
      path: '/pinky-detect'
      fullPath: '/admin/pinky-detect'
      preLoaderRoute: typeof AdminAuthedPinkyDetectRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/chat': {
      id: '/admin/_authed/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminAuthedChatRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/camera': {
      id: '/admin/_authed/camera'
      path: '/camera'
      fullPath: '/admin/camera'
      preLoaderRoute: typeof AdminAuthedCameraRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/buzzer': {
      id: '/admin/_authed/buzzer'
      path: '/buzzer'
      fullPath: '/admin/buzzer'
      preLoaderRoute: typeof AdminAuthedBuzzerRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/arm/': {
      id: '/admin/_authed/arm/'
      path: '/arm'
      fullPath: '/admin/arm/'
      preLoaderRoute: typeof AdminAuthedArmIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/tables': {
      id: '/admin/_authed/dev/tables'
      path: '/dev/tables'
      fullPath: '/admin/dev/tables'
      preLoaderRoute: typeof AdminAuthedDevTablesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/server-ops': {
      id: '/admin/_authed/dev/server-ops'
      path: '/dev/server-ops'
      fullPath: '/admin/dev/server-ops'
      preLoaderRoute: typeof AdminAuthedDevServerOpsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/erd': {
      id: '/admin/_authed/dev/erd'
      path: '/dev/erd'
      fullPath: '/admin/dev/erd'
      preLoaderRoute: typeof AdminAuthedDevErdRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/architecture': {
      id: '/admin/_authed/dev/architecture'
      path: '/dev/architecture'
      fullPath: '/admin/dev/architecture'
      preLoaderRoute: typeof AdminAuthedDevArchitectureRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dev/api-docs': {
      id: '/admin/_authed/dev/api-docs'
      path: '/dev/api-docs'
      fullPath: '/admin/dev/api-docs'
      preLoaderRoute: typeof AdminAuthedDevApiDocsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/arm/joint-control': {
      id: '/admin/_authed/arm/joint-control'
      path: '/arm/joint-control'
      fullPath: '/admin/arm/joint-control'
      preLoaderRoute: typeof AdminAuthedArmJointControlRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedBuzzerRoute: typeof AdminAuthedBuzzerRoute
  AdminAuthedCameraRoute: typeof AdminAuthedCameraRoute
  AdminAuthedChatRoute: typeof AdminAuthedChatRoute
  AdminAuthedPinkyDetectRoute: typeof AdminAuthedPinkyDetectRoute
  AdminAuthedRobotRoute: typeof AdminAuthedRobotRoute
  AdminAuthedRobotsRoute: typeof AdminAuthedRobotsRoute
  AdminAuthedUsersRoute: typeof AdminAuthedUsersRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedArmJointControlRoute: typeof AdminAuthedArmJointControlRoute
  AdminAuthedDevApiDocsRoute: typeof AdminAuthedDevApiDocsRoute
  AdminAuthedDevArchitectureRoute: typeof AdminAuthedDevArchitectureRoute
  AdminAuthedDevErdRoute: typeof AdminAuthedDevErdRoute
  AdminAuthedDevServerOpsRoute: typeof AdminAuthedDevServerOpsRoute
  AdminAuthedDevTablesRoute: typeof AdminAuthedDevTablesRoute
  AdminAuthedArmIndexRoute: typeof AdminAuthedArmIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedBuzzerRoute: AdminAuthedBuzzerRoute,
  AdminAuthedCameraRoute: AdminAuthedCameraRoute,
  AdminAuthedChatRoute: AdminAuthedChatRoute,
  AdminAuthedPinkyDetectRoute: AdminAuthedPinkyDetectRoute,
  AdminAuthedRobotRoute: AdminAuthedRobotRoute,
  AdminAuthedRobotsRoute: AdminAuthedRobotsRoute,
  AdminAuthedUsersRoute: AdminAuthedUsersRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedArmJointControlRoute: AdminAuthedArmJointControlRoute,
  AdminAuthedDevApiDocsRoute: AdminAuthedDevApiDocsRoute,
  AdminAuthedDevArchitectureRoute: AdminAuthedDevArchitectureRoute,
  AdminAuthedDevErdRoute: AdminAuthedDevErdRoute,
  AdminAuthedDevServerOpsRoute: AdminAuthedDevServerOpsRoute,
  AdminAuthedDevTablesRoute: AdminAuthedDevTablesRoute,
  AdminAuthedArmIndexRoute: AdminAuthedArmIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
